config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]

	resources :users
	resources :articles do
		resources :comments
	end
	root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
	validates :title, presence: true, 
                            length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :articles, dependent: :destroy
  has_many :comments

  validates :email_address, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :user_name, uniqueness: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end
	def show
    @article = Article.find(params[:id])
	end
	def new
		@article = Article.new
	end
	 
  def create
    @article = Article.new(article_params)
    @article[:user_id] = current_user.id

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end
	def edit
    @article = Article.find(params[:id])
	end
	
	def update
		@article = Article.find(params[:id])
		if validate_user && @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	def destroy
		if validate_user
			@article = Article.find(params[:id])
			@article.destroy

			redirect_to articles_path
		end
	end

	def validate_user
		@article = Article.find(params[:id])
		@article.user.id == current_user.id
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
    if current_user.id
			@comment_params = comment_params
			@comment_params[:user_id] =current_user.id
			@comment = @article.comments.create(@comment_params)
		end

      redirect_to article_path(@article)
	end

  def destroy
    if validate_user
      @article = Article.find(params[:article_id])
      @comment = Comment.find(params[:id])
      @comment.destroy

      redirect_to article_path(@article)
    end
  end

  def validate_user
		@comment = Comment.find(params[:id])
		@comment.user.id == current_user.id
	end
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.where(user_name: params[:user_name]).first
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "username or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
  private
    def password
      if params[:password] == params[:password_confirmation]
        params[:password]
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
    @user = User.new(user_params)
    if @user.save 
      @user.save
			redirect_to @user
    else
			render 'new'
    end
  end
		def show
			@user = User.find(params[:id])
		end
  private
    def user_params
      if params[:user][:password] == params[:user][:password_confirmation]
        params.require(:user).permit(:user_name, :email_address, :password, :password_confirmation)
      end
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_with(model: @article, local: true) do |form|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    = form.label :title
    %br/
    = form.text_field :title
  %p
    = form.label :text
    %br/
    = form.text_area :text
  %p
    = form.submit

app/views/articles/edit.html.haml
%h1 Edit article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles
%table
	%tr
		%th ID
		%th User
		%th Title
		%th Text
		%th
		%th
		%th
		- @articles.each do |article|
			%tr
				%td= article.id
				%td= article.user.user_name
				%td= article.title
				%td= article.text
				%td= link_to 'Show', article_path(article)
				-if article.user.id == current_user&.id
					%td= link_to 'Edit', edit_article_path(article)
					%td= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }

-if current_user&.id
	%p= link_to 'New Article', new_article_path()

app/views/articles/new.html.haml
%h1 new article
-if current_user&.id
  = render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
	%strong ID:
	= @article.id
%p
	%strong User:
	= @article.user.user_name
%p
	%strong Title:
	= @article.title
%p
	%strong Text:
	= @article.text

%table
	%tr
	%th ID
	%th User
	%th Comment
	%th
	- @article.comments.each do |comment|
		%tr
			%td= comment.id
			%td= comment.user.user_name
			%td= comment.body
			-if comment.user.id == current_user&.id
				%td= link_to 'Delete Comment', [comment.article, comment],
														method: :delete, data: { confirm: 'Are you sure?' }
-if current_user&.id
	%h2 Add a comment:
	= form_with(model: [ @article, @article.comments.build ], local: true) do |form|
		%p
			= form.label :body
			%br/
			= form.text_area :body
		%p
			= form.submit

-if @article.user.id == current_user&.id
	%p= link_to 'Edit', edit_article_path(@article)
%p= link_to 'Back', articles_path()

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SimpleBlog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      Logged in as #{current_user.user_name}.
      \#{link_to "Log Out", logout_path}
    - else
      = link_to "Sign Up", signup_path
      or
      =link_to "Log In", login_path

    = yield

app/views/users/new.html.haml
= form_with(model: @user, local: true) do |form|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited
        this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %p
    = form.label :user_name
    %br/
    = form.text_field :user_name
  %p
    = form.label :email_address
    %br/
    = form.text_field :email_address
  %p
    = form.label :password
    %br/
    = form.text_area :password
  %p
    = form.label :password_confirmation
    %br/
    = form.text_area :password_confirmation
  %p
    = form.submit

app/views/users/show.html.haml
%p
	%strong user:
	= @user.user_name
%p
	%strong email:
	= @user.email_address

app/views/welcome/index.html.haml
%h1 Hello, Rails!